env: "prod"
mainStorage_db_driver: "postgres"
sessionsStorage_db_driver: "postgres"
access_token_ttl: 15m
refresh_token_ttl: 24h
grpc:
  host: 0.0.0.0
  port: 44044
  timeout: 10s
gateway:
  gateway_port: 50000
  enabled: true
  timeout: 10s
  idle_timeout: 120s
urlService:
  host: url_service
  port: 8082

